version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/your_database_name
      SPRING_DATASOURCE_USERNAME: your_database_username
      SPRING_DATASOURCE_PASSWORD: your_database_password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: perpustakaan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "54320:54320"
